"""new fields in post model

Revision ID: 5448aa751b4f
Revises: 730194c41283
Create Date: 2020-05-24 17:52:17.640046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5448aa751b4f'
down_revision = '730194c41283'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('author', sa.String(length=20), nullable=True))
    op.add_column('post', sa.Column('title', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'title')
    op.drop_column('post', 'author')
    # ### end Alembic commands ###
