"""new fields in user model

Revision ID: 730194c41283
Revises: 0c17f44ef6ca
Create Date: 2020-05-24 17:00:33.776655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '730194c41283'
down_revision = '0c17f44ef6ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
