"""rename athor to writer

Revision ID: ffdaec03a776
Revises: 5448aa751b4f
Create Date: 2020-05-24 18:06:30.128336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffdaec03a776'
down_revision = '5448aa751b4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('writer', sa.String(length=20), nullable=True))
    op.drop_column('post', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('author', sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.drop_column('post', 'writer')
    # ### end Alembic commands ###
